hyperweb-io/cosmos-kit

- LICENSE-Apache
- LICENSE-MIT
- packages/core/LICENSE-Apache
- packages/core/LICENSE-MIT
- packages/react/LICENSE-Apache
- packages/react/LICENSE-MIT
add licenses from https://github.com/chainapsis/cosmodal/commit/0509d334573379eeefc0e5ca4b11e44bbc64cbee
> add cosmodal licenses

- packages/core/src/chainInfo.ts
The chain info objects were not being properly transformed to the format Keplr expects for experimentally suggesting chain. Let's fix that.
> Fix chain info format for suggesting chain

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/cosmostation/CHANGELOG.md
- packages/cosmostation/package.json
- packages/docs/CHANGELOG.md
- packages/docs/package.json
- packages/example/CHANGELOG.md
- packages/example/package.json
- packages/keplr/CHANGELOG.md
- packages/keplr/package.json
- packages/leap/CHANGELOG.md
- packages/leap/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- @cosmos-kit/core@0.20.1
- @cosmos-kit/cosmostation@0.2.1
- docs@1.0.1
- @cosmos-kit/example@0.20.6
- @cosmos-kit/keplr@0.20.1
- @cosmos-kit/leap@0.2.1
- @cosmos-kit/react@0.19.1
> chore(release): publish

- packages/core/src/types/hook.ts
- packages/core/src/types/wallet.ts
- packages/core/types/types/hook.d.ts
- packages/core/types/types/wallet.d.ts
- packages/example/pages/add-cw20.tsx
- packages/react-lite/src/utils.ts
- wallets/cosmostation-extension/src/extension/client.ts
- wallets/cosmostation-extension/types/extension/client.d.ts
- wallets/keplr-extension/src/extension/client.ts
- wallets/keplr-extension/types/extension/client.d.ts
- wallets/leap-extension/src/extension/client.ts
- wallets/leap-extension/src/extension/types.ts
- wallets/leap-extension/types/extension/client.d.ts
- wallets/leap-extension/types/extension/types.d.ts
Hello, as described in issue #177 ,I am working on an implementation for CW20 token suggestion, if you have any feedback or suggestions I am open to any discussion, thanks!
> Feat: Suggest CW20 Token

- wallets/leap-extension/package.json
- wallets/leap-extension/src/extension/client.ts
- wallets/leap-extension/src/extension/types.ts
- yarn.lock
> feat: Add Leap Suggest Chain

- wallets/compass-extension/src/extension/client.ts
- wallets/compass-extension/src/extension/types.ts
- wallets/compass-extension/types/extension/client.d.ts
- wallets/compass-extension/types/extension/types.d.ts
- wallets/leap-extension/src/extension/client.ts
- wallets/leap-extension/src/extension/types.ts
- wallets/leap-extension/types/extension/client.d.ts
- wallets/leap-extension/types/extension/types.d.ts
Adds signArbitrary to leap and compass clients.
> Add signArbitrary to leap extension client.

- packages/core/src/manager.ts
At times, due to a race condition in `WalletManager.onMounted`, the `MainWalletBase.initClient` executes multiple times, creating unpredictable bugs and edge cases. This PR resolves the race condition by adding the necessary `await` calls and only restoring the account whenever the wallets have been initialized.
> fix: `await` Async Operations in `WalletManager.onMounted`

- wallets/shell-extension/README.md
- wallets/shell/README.md
In this PR we change the text. Can you review for us?
Also, can you please tell us how to publish our Shell Wallet on your npm?
Thank you in advance.
> Change text in README 

- README.md
@twhy In this PR we updated README file. Can you review it for us?
Also, it has been more than a week since we updated the new README file but it has not been published on npm yet. Can you please check this case for us again?
Thank you in advance.
> Update README Shell wallet

- packages/example/package.json
- packages/react/package.json
- packages/react/src/modal/components/views/QRCode.tsx
- packages/react/src/modal/modal.tsx
- yarn.lock
- bump interchain-ui version
- fix undefined runtime error below
> fix: improve dependency bundle size and fix undefined error

- wallets/fin/package.json
Update Fin Wallet bundle module in packages.json
> Update Fin Wallet bundle module

- wallets/fin-extension/src/extension/registry.ts
Update Fin Wallet naming and Connect Event Names
> Update fin naming and Connect Event Names

- wallets/cosmos-extension-metamask/src/extension/client.ts
Adds sign arbitrary wrapper to snap client per request from dapps.
> Request to add sign arbitrary to snap client

- packages/docs/pages/get-started.mdx
- packages/docs/pages/hooks/index.mdx
- packages/docs/pages/hooks/use-chain-wallet.mdx
- packages/docs/pages/hooks/use-chain.mdx
- packages/docs/pages/hooks/use-chains.mdx
- packages/docs/pages/hooks/use-manager.mdx
- packages/docs/pages/index.mdx
- packages/docs/pages/migration-to-v2.mdx
> docs: fix typos

- packages/react-lite/src/hooks/useIframe.ts
The new nestable iframe functionality allows overriding specific wallet methods so that the outer app can manually handle and wrap messages in any way it wants. However, it still requires a wallet to be connected.
This PR makes it so the outer app does not need to have a connected wallet for this wallet client method substitution to occur.
This is necessary because there are use cases where the outer app may be fully operating as a different account, unrelated to the connected wallet, like in DAO DAO. DAO DAO needs a connected wallet so that it can propose messages to a DAO, but it does not need a connected wallet while the user is interacting with an iframe app, since DAO DAO makes the app think the DAO itself is connected. It is confusing that the user has to login with their own wallet …
> Allow iframe method override without login

- wallets/leap-extension/src/extension/client.ts
- wallets/leap-extension/src/extension/types.ts
- updating client.ts to use suggestCW20Token for adding CW20 token.
> update suggestToken with suggestCW20Token for leap-extension

- packages/docs/components/react/chain-dropdown.tsx
This fixes internal issue #561
> fix(docs): zIndex issue in chain dropdown

- packages/cosmos-kit/src/wallets.ts
- wallets/trust/src/index.ts
Add Trust Extension to Wallet list.
Hey there, this is Jeff from Trust, we are happy to announce we will support Cosmos dApps in the next version of our Extension Wallet, we would like to enable the connector. Thanks.
> feat: Add support for Trust Extension

- wallets/leap-metamask-cosmos-snap/src/extension/utils.ts
- Fix typo in Metamask detection (#398)
> fix: typo in leap-metamask-cosmos-snap detection

- wallets/leap-capsule-social-login/README.md
This PR includes some additional context and links to make the Capsule Variables more intuitive to obtain and include
> Update Social Login Readme to include more information on Capsule Variables

- packages/core/package.json
- packages/react-lite/package.json
- packages/react/package.json
- yarn.lock
> upgrade chain registry types

- packages/core/__tests__/manager.test.ts
- packages/core/__tests__/repository.test.ts
Testing/add unit test/wallet repo 9
> Testing/add unit test/wallet repo 9

- packages/core/__tests__/bases/main-wallet.test.ts
- packages/core/__tests__/bases/wallet.test.ts
- packages/core/__tests__/manager.test.ts
- packages/core/__tests__/name-serveice-class.test.ts
- packages/core/__tests__/repository.test.ts
- packages/core/package.json
- packages/core/src/bases/main-wallet.ts
- packages/core/test-utils/mock-extension/extension/chain-wallet.ts
- packages/core/test-utils/mock-extension/extension/client.ts
- packages/core/test-utils/mock-extension/extension/main-wallet.ts
- packages/core/test-utils/mock-extension/extension/registry.ts
- packages/core/test-utils/mock-extension/extension/types.ts
- packages/core/test-utils/mocker/index.ts
- yarn.lock
Testing/add unit test/wallet 7
> Testing/add unit test/wallet 7

- .github/workflows/run-tests.yml
- packages/example/pages/wallet-manager.tsx
- packages/react-lite/__test__/useChain.test.tsx
- packages/react-lite/__test__/useChainWallet.test.tsx
- packages/react-lite/__test__/useChains.test.tsx
- packages/react-lite/__test__/useManager.test.tsx
- packages/react-lite/__test__/useNameService.test.tsx
- packages/react-lite/__test__/useWallet.test.tsx
- packages/react-lite/__test__/useWalletClient.test.tsx
- packages/react-lite/jest.config.js
- packages/react-lite/jest.setup.js
- packages/react-lite/package.json
- packages/react-lite/test-utils/chain-provider-wrapper.tsx
- packages/react-lite/test-utils/custom-render-hook.tsx
- packages/react-lite/test-utils/index.ts
- yarn.lock
> add unit test for react-lite

- packages/example/package.json
- packages/example/pages/_app.tsx
- wallets/leap-capsule-social-login/package.json
- wallets/leap-capsule-social-login/src/main-wallet.ts
- yarn.lock
Updates below packages:
```
"@leapwallet/cosmos-social-login-capsule-provider": "0.0.39",
"@leapwallet/cosmos-social-login-capsule-provider-ui": "0.0.56",
```
> update leap-capsule packages

- packages/core/__tests__/manager.test.ts
- packages/core/src/manager.ts
fix addChains logical issue and make test pass
> fix addChains logical issue and make test pass

- packages/react/src/context/useSelectedWalletContext.tsx
- packages/react/src/modal/components/views/WalletList.tsx
- packages/react/src/modal/modal.tsx
connected state not working on initial render
after we use a global context to save what current wallet user choose.
so we need to restore what wallet user choose from local storage if user has choose before.
> connected state not working on initial render

- packages/react-lite/src/provider.tsx
- packages/react/src/provider.tsx
Adds localhost and Abstract urls for interacting with iFrames.
> Add localhost and Abstract iframe URLs

- wallets/web3auth/src/extension/utils.ts
Error handling in the web3auth extension utils file was accidentally removed. 
This includes error logging in `listenOnce` and the try catch block that logs but ignores irrelevant errors but throws relevant ones in `connectClientAndProvider`
> fix: add back error handling in web3auth utils

- wallets/exodus-extension/CHANGELOG.md
- Corrected "formating" to "formatting" in `CHANGELOG.md`.
> Fix/typo  CHANGELOG.md

- packages/docs/pages/index.mdx
- Fixed a typo in `index.mdx`:
- Corrected "univeral" to "universal" for consistency.
> fix  index.mdx

- packages/docs/pages/hooks/use-manager.mdx
There are Typographical Errors in document
`ManagerConext` => `ManagerContext`
> Fix Typo in Documentation

- packages/walletconnect/src/utils/core.ts
- wallets/shell-extension/src/extension/types.ts
Hello Team! I fixes some typos.
> chore: fix typos
