hyperweb-io/cosmos-kit

packages/react/README.md
This change just updates the readme in the `@cosmos-kit/react` package to be accurate.
=> Update Readme to latest changes

packages/react/src/hooks.ts
Fixes #144.
I'm not sure why the `getOfflineSigner...` methods in particular were not working, but they do after this.
=> fix getOfflineSignerAmino

packages/docs/pages/get-started.mdx, packages/docs/pages/use-chain.mdx
Fix the `ChainConext` typo in the docs and rename occurrences into `ChainContext`
=> docs: fix `ChainConext` typo

wallets/leap-extension/src/extension/registry.ts
Add connectEventNameOnWindow in the leap-extension registry so that Cosmos-kit is in sync with account changes on leap-extension.
=> Add leap keystore change event

packages/core/src/bases/chain-wallet.ts, packages/core/src/types/manager.ts, packages/core/src/utils/endpoint.ts
Allows disabling endpoint validation to avoid long waiting times before signing a transaction. Currently, the application enforces strict endpoint validation for outgoing transactions, which can lead to extended wait times for users when signing transactions.
At [Osmosis](https://github.com/osmosis-labs/osmosis-frontend), we are using in-house RPC/Rest endpoints. Since we have control of our endpoints, we would like to be able to sign/broadcast transactions without undergoing a 200 ms delay per transaction.
=> feat: Allow Disabling Endpoint Validation

wallets/station-extension/src/extension/client.ts
Station is currently showing the terra address no matter which chain is selected, this PR should fix it.
=> FIX: Show correct address based on the desired chain on Station

wallets/station-extension/src/extension/client.ts
Fixes getting wallet address by chain id from station wallet. The current version throws an error since `account.addresses` is not defined
=> fix: Get Correct Station Address by Chain ID

.github/workflows/run-tests.yml, wallets/station-extension/package.json
hope syntax ok, this (should) fix 
`> error @terra-money/feather.js@1.0.3: 
The engine "node" is incompatible with this module. Expected version ">=18". Got "16.14.0"`
as defined by feather.js package.json now >=18, build and ship failing
=> Update run-tests.yml for node lts

packages/core/src/types/wallet.ts, packages/core/types/types/wallet.d.ts, wallets/keplr-extension/src/extension/client.ts, wallets/keplr-extension/types/extension/client.d.ts, wallets/vectis-extension/package.json, wallets/vectis-extension/src/extension/client.ts, wallets/vectis-extension/src/extension/registry.ts, wallets/vectis-extension/src/extension/types.ts, wallets/vectis-extension/src/extension/utils.ts, wallets/vectis-extension/types/extension/client.d.ts, wallets/vectis-extension/types/extension/types.d.ts, yarn.lock
The previous image was broken and I include an image in IPFS and also update some methods of our extension.
Additionally I added signArbitrary method which is used for sign an arbitrary message in order to let access to your frontend for example. (https://docs.cosmos.network/v0.47/architecture/adr-036-arbitrary-signature)
I also added a new property to WalletAccount interface `isSmartContract` to let other wallet to differentiate between EOA and smart contract account.  Another suggestion for the same key could be `isSmartAccount` or in our case `isVectisAccount`
Although Keplr include an verifyArbitrary and it is a safe method, I think is frontend responsibility to do that verification without the help of the extension.
=> feat: update vectis image and methods & support for sign arbitrary and smart contract wallets

wallets/leap-mobile/src/wallet-connect/registry.ts
Updates leap mobile project id to fix wallet connect error on mobile browsers.
=> update leap mobile project id

wallets/keplr-mobile/src/wallet-connect/registry.ts, wallets/leap-mobile/src/wallet-connect/registry.ts, wallets/leap/package.json
Add missing `leap-mobile` dependency in `@cosmos-kit/leap`.
Eliminate `react-icons` from the `leap-mobile` registry. It appears that these icons aren't utilized anywhere within the cosmos-kit codebase. Additionally, `react-icons` bloats the bundle size. If necessary, we could consider adding their SVGs inline.
=> feat: Remove Icons from Leap Mobile Registry and Add Missing Dependencies for `@cosmos-kit/leap`

packages/core/src/bases/chain-wallet.ts
This PR aims to fix an error when trying to get the rest endpoint. It adds same optional chaining operator as `getRpcEndpoint`.
=> fix: Add Optional Chaining to Get Rest Endpoint

packages/core/src/bases/wallet.ts
Current disconnection can be inaccurate since the wallet state is reset before the client disconnects successfully. This can create unexpected situations for wallets needing a remote request to disconnect like WalletConnect.
=> fix: Reset After Disconnect is Successful

packages/core/src/manager.ts
If a user tries to connect to the wallet and reloads the page, it will automatically try to reconnect even if the connection was unsuccessful. This can result in unexpected errors and results like trying to connect to WalletConnect even if the user rejects the approval. This PR fixes this issue by checking that the account localstorage string is not empty.
=> fix: Do Not Reconnect Wallet if There Are No Accounts

.vscode/cosmos-kit.code-workspace
[VSCode workspaces](https://code.visualstudio.com/docs/editor/workspaces) allow first class treatment of mono repos.
Details are in the link above, but I've found it to be most beneficial for:
* Allowing extensions to treat each workspace as a root (rather than the mono repo root). This fixes many extensions that weren't built with mono repos in mind, such as the Jest extension
* Hides some of the seldom-touched files in root. Helps VSCode focus on the most important files.
To open, navigate to the `.code-workspace` file and click "Open Workspace" in the bottom right corner. VSCode will remember this workspace as though it were a folder.
=> (Dev UX) feat: code workspace

wallets/keplr-extension/src/extension/main-wallet.ts, wallets/keplr-extension/src/extension/registry.ts
The Keplr Mobile in-app browser provides `window.keplr`, similar to the extension on desktop browsers, with a `mode` set to `mobile-web`. This PR sets the `mobileDisabled` property to `false` for the Keplr extension wallet when in the context of the Keplr Mobile in-app browser.
=> Fix Keplr Mobile in-app browser support

wallets/web3auth/src/extension/client.ts, wallets/web3auth/src/extension/utils.ts
There is a bug in the web3auth wallet where it opens a ton of tabs randomly (when trying to disconnect in the background I think, though I can't reproduce it consistently). The disconnect logic was trying to connect first in order to disconnect. Now it should not do that.
=> Fix web3auth wallet tab spam

wallets/cosmostation-extension/src/extension/client.ts, wallets/keplr-extension/src/extension/client.ts, wallets/okxwallet-extension/src/extension/client.ts, wallets/okxwallet-extension/src/extension/types.ts, wallets/station-extension/src/extension/client.ts, wallets/xdefi-extension/src/extension/client.ts
Add `signArbitrary` to OkxClient since it's available on its window object and Osmosis needs it to enable notifications.  
Furthermore, add missing sign methods to individual wallets.
=> feat: Add `signArbitrary` to OKX and Missing Sign Methods To Wallet Clients

wallets/station-extension/src/extension/utils.ts
Fixed an issue with the Station wallet. On its first load, it would throw a "client not found" error because the station window property wasn't available. Additionally, the event callback was referencing an initially declared variable that was set to "undefined" due to the missing window property.
=> fix: Station Initial Connect

wallets/cosmostation-extension/src/extension/client.ts
Refactored the `signAmino` and `signDirect` methods to check for the existence of `ikeplr` signing functions upfront. This eliminates the reliance on error-catching to determine the signing method, solving an issue where users saw two popups when rejection transactions.
=> fix: Cosmostation Couble Sign Pop Up

packages/core/src/types/wallet.ts, packages/walletconnect/src/client.ts, wallets/keplr-mobile/src/wallet-connect/registry.ts
Keplr Mobile Android uses `intent://` when it is a Deeplink. I attach the link below. 
https://github.com/chainapsis/keplr-wallet/blob/71f0ff84b9de8f7180847e2536f3206241ce926f/packages/wc-qrcode-modal/src/modal.tsx#L61
When communicating with Wallet connect from Keplr, we use some methods from Keplr. The related code links are below.
https://github.com/chainapsis/keplr-wallet/blob/71f0ff84b9de8f7180847e2536f3206241ce926f/packages/wc-qrcode-modal/src/index.tsx#L14
Add an option to use them.
=> Fix wallet connect for Keplr Mobile Android

packages/core/src/iframe/extension/client.ts, packages/core/src/iframe/extension/registry.ts, packages/core/src/manager.ts, packages/core/src/types/iframe.ts, packages/react-lite/src/hooks/useIframe.ts
This fixes the iframe wallet not detecting the outer wallet connection change and autoconnecting/autodisconnecting where appropriate.
This also fixes the bug where the outer wallet's metadata (name and logo) would stick around after the outer wallet disconnects.
=> Fix iframe autoconnect on outer wallet change

packages/core/src/manager.ts, packages/react-lite/src/hooks/useIframe.ts
There was a bug where the outer window controlling a nested iframe was trying to dispatch an event on the iframe, which is blocked when their origins differ. This PR fixes it by using the allowed `postMessage` function on the outer window and making the iframe window rebroadcast the message as an event internally.
=> Fix iframe cross-origin messaging bug

packages/react-lite/src/hooks/useIframe.ts
I thought I fixed this in #339, but in my haste I missed a critical parameter needed to allows the keystorechange event to be posted to any origin in the iframe. It is safe to use a wildcard origin because there is no sensitive information in the event.
=> Fix iframe origin bug AGAIN

wallets/cosmostation-extension/src/extension/utils.ts, wallets/keplr-extension/src/extension/utils.ts, wallets/xdefi-extension/src/extension/utils.ts
Fixed an issue with the Keplr, Cosmostation, and Xdefi wallet. On its first load, it would throw a "client not found" error because the station window property wasn't available. Additionally, the event callback was referencing an initially declared variable that was set to "undefined" due to the missing window property.
Similar to #314
=> fix: Race Condition When Getting Wallet When Document State Changes

wallets/keplr-mobile/src/wallet-connect/registry.ts, wallets/leap-mobile/src/wallet-connect/registry.ts
This fixes the Keplr Mobile deep-linking on mobile. It's been broken for a while.
While the URL intent is configured correctly in the `registry.ts` walletconnect options, the WalletConnect Cloud's API response with wallet info takes precedence, which is here:
```
{
"listings": {
"6adb6082c909901b9e7189af3a4a0223102cd6f8d5c39e39f3d49acb92b578bb": {
"id": "6adb6082c909901b9e7189af3a4a0223102cd6f8d5c39e39f3d49acb92b578bb",
"name": "Keplr",
"slug": "keplr",
"description": "Keplr is the largest Interchain wallet in the Cosmos ecosystem, supporting ",
"homepage": "https://keplr.app",
"chains": [
"cosmos:columbus-4",
"cosmos:cosmoshub-4",
"cosmos:irishub-1",
"cosmos:kava-4",
"cosmos:likecoin-mainnet-2"
],
"versions": [
"1",
"2"
],
"sdks": [
"sign_v1",
"sign_v2"
],
"app_type": "wallet", …
```
=> Fix Keplr Mobile deep link URL

packages/docs/pages/get-started.mdx, packages/docs/pages/hooks/use-chain-wallet.mdx, packages/docs/pages/hooks/use-chain.mdx, packages/walletconnect/src/client.ts, wallets/coin98-extension/src/extension/client.ts, wallets/compass-extension/src/extension/client.ts, wallets/cosmos-extension-metamask/src/extension/client.ts, wallets/cosmostation-extension/src/extension/client.ts, wallets/fin-extension/src/extension/client.ts, wallets/frontier-extension/src/extension/client.ts, wallets/keplr-extension/src/extension/client.ts, wallets/leap-extension/src/extension/client.ts, wallets/leap-metamask-cosmos-snap/src/extension/client.ts, wallets/okxwallet-extension/src/extension/client.ts, wallets/shell-extension/src/extension/client.ts, wallets/xdefi-extension/src/extension/client.ts
This changes the `preferNoSetFee` flag default to `false` for all wallets.
I noticed this was added and defaulted to `true` in https://github.com/cosmology-tech/cosmos-kit/commit/af1cbac3588f50f250fa65fc4fba9fda2844689a, but I don't understand why. I believe this is going to break most dApps, requiring them to manually call `wallet.client.setDefaultSignOptions({ preferNoSetFee: false })` for the connected wallet every time if they want fees to be selected (right now this default is requiring the user to manually choose a fee in Keplr). This is unexpected behavior and not a sensible default as far as I can tell.
If I'm misunderstanding something, please let me know 🙏
=> Default `preferNoSetFee` to `false`

packages/core/src/iframe/extension/main-wallet.ts, packages/core/src/iframe/extension/utils.ts, packages/core/src/manager.ts
This fixes the iframe implementation so that it allows for infinite recursion of iframes. Instead of using `window.top`, which always points to the outermost window, the iframe should be exchanging messages with its parent window, `window.parent`. This replaces `window.top` references with `window.parent`, which ensures a double or more-nested iframe still works.
Just because this is how it should work, architecturally, and not because it needs to work this way.
=> Allow infinite iframe recursion

packages/react/src/index.ts
The `useIframe` hook was not re-exported in the full react version of cosmos-kit.
=> Export useIframe hook from cosmos-kit react

packages/core/src/bases/state.ts, packages/core/src/repository.ts
All non-existent wallets immediately enter NotExist state on init. Because of that, I think it needs to stop treating non-existent wallets as if they were once connected or are the current wallet. I'm not exactly sure how, but I think `current` being stuck on a non-existent wallet is preventing other wallets from connecting, and this seems to fix it.
=> Don't treat non-existent wallets as if they were connected

wallets/leap-metamask-cosmos-snap/src/extension/main-wallet.ts, wallets/leap-metamask-cosmos-snap/src/extension/utils.ts
- Add Metamask detection to `leap-metamask-cosmos-snap`, so that custom modals can detect that Metamask is installed, similar to other wallets like Keplr, Cosmostation, Leap.
=> feat: add Metamask detection to leap-metamask-cosmos-snap

packages/core/src/bases/state.ts, packages/core/src/repository.ts
- Avoid setting wallets with `walletStatus === 'NotExist'` as current. If Cosmostaion is not installed, `CosmostationClient` sets this status right after init. This prevents some other wallets (e.g. Leap) from connecting.
- Remove `isWalletNotExist` from `isWalletOnceConnect` to align with the changes above.
=> fix: installed wallets detection

wallets/leap-metamask-cosmos-snap/src/extension/client.ts
**Issue:** 
When calling signDirect on Leap Cosmos Metamask Snaps (v0.6.1), we are getting following error:
`TypeError: Cannot read properties of undefined (reading 'authInfoBytes')
at CosmosSnapClient.signDirect`
**Cause:** 
There should be `await` in this [line](https://github.com/cosmology-tech/cosmos-kit/blob/efbf059a79454b2a7992f63b8ea3d4f21d7d6634/wallets/leap-metamask-cosmos-snap/src/extension/client.ts#L115).
`requestSignature` from ['@leapwallet/cosmos-snap-provider'](https://github.com/leapwallet/cosmos-metamask-snap/blob/6abebb540c72a1fcec05922bae9142b77c730ea0/packages/cosmos-snap-provider/src/snap.ts#L130) is an async function.
**Fix:**
Add `await` before `requestSignature`.
=> fix: Leap Metamask Snaps signDirect - cannot read properties of undefined 'authInfoBytes' issue

packages/core/package.json, packages/react-lite/package.json, packages/react/package.json, wallets/station-extension/package.json, wallets/web3auth/package.json, yarn.lock
Don't force clients to use an old version of @chain-registry packages.
=> Move @chain-registry/types package imports to peer dependencies

packages/react/src/context/index.ts, packages/react/src/context/useSelectedWalletContext.tsx, packages/react/src/modal/components/views/WalletList.tsx, packages/react/src/modal/modal.tsx, packages/react/src/provider.tsx
use a context to save what wallet user select, do not rely on current function in wallet manager 
history
https://github.com/cosmology-tech/cosmos-kit/commit/f52b5a7a64b1a6021b517baf06de6400e6719092#diff-670fa40d614a5dda9b8e6[%E2%80%A6]3c6bbd2a091dddfc6R160-R165
=> fix install wallet instruction modal, don't pop up when click wallet icon

wallets/keplr-extension/src/extension/index.ts
I deleted the `utils` directory from https://github.com/cosmology-tech/cosmos-kit/pull/460 PR and forgot to delete the import.
=> Fix `kelpr-extension` impoting

wallets/keplr-mobile/src/wallet-connect/client.ts
When connecting the `Keplr Mobile` wallet with `Wallect Connect`, I set it to connect to an `existing session` if one exists.
For examples, proceed to the example source in cosmos-kit.
1. The connection works fine when there are no sessions.
[![first connect]()](https://github.com/cosmology-tech/cosmos-kit/assets/32606183/d5bf7ec5-9be8-47c2-9d79-db99530af784)
2. However, if you refresh the page after connecting, it will request connect multiple times due to the source below in the `packages/react-lite/src/hooks/useChain.ts` file.
```typescript
// temporary solution for sync not working when the used chain is changed without page rendering (only component rendering)
useEffect(() => {
const currentWallet = window.localStorage.getItem(
'cosmos-kit@2:core//current-wallet'
);
if (
sync && …
```
=> Add check connectable session before connect to mobile on `Keplr Mobile`

packages/core/src/types/hook.ts, packages/react-lite/src/utils.ts
the chain wallet context provided by `@cosmjs/react-lite` uses `clientMethodAssert` to cleanly throw descriptive errors when the wallet or client is undefined, but it's missing the case where the function is undefined because of a missing optional chain before `.bind`.
this fixes it so that it handles undefined function errors as intended.
it also fixes an incorrect type in the core that may be potentially undefined.
=> fix: missing optional chaining and incorrect type

packages/core/package.json, packages/core/src/cosmiframe/cosmiframe.ts, packages/core/src/cosmiframe/extension/types.ts, packages/core/src/manager.ts, packages/react-lite/package.json, packages/react-lite/src/hooks/useIframe.ts, packages/react-lite/src/provider.tsx, packages/react/package.json, packages/react/src/provider.tsx, yarn.lock
This adds the following to the `useIframe` hook:
- return a function to trigger the iframe wallet keystore change event so that the calling app can inform the nested iframe app that wallet details have changed
- return the iframe instance so that the caller can interact directly with the saved iframe ref, avoiding the need to save duplicates
This also updates to the latest Cosmiframe, to enable chain ID specific signer overrides as well as regex origins.
=> improve iframe functionality

wallets/ledger/package.json, wallets/ledger/src/index.ts, wallets/ledger/src/web-usb-hid/chain-wallet.ts, wallets/ledger/src/web-usb-hid/client.ts, wallets/ledger/src/web-usb-hid/main-wallet.ts, wallets/ledger/src/web-usb-hid/registry.ts, wallets/ledger/src/web-usb-hid/utils.ts, yarn.lock
- Fixes the missing `getOfflineSigner` implementation
- Fixes `StdSignDoc` serialization to JSON. The object MUST be serialized in lexicographical key order [1]
- Replace the encoding of `pubkey` in `getAccount` from a `TextEncoder` to using the `fromHex` function
- Bump `@ledgerhq/*` dependencies
- Prettify
Fixes #497 
[1]: https://github.com/cosmos/ledger-cosmos/blob/main/docs/TXSPEC.md#validation
=> fix: ledger wallet

wallets/web3auth/src/extension/types.ts, wallets/web3auth/src/extension/utils.ts
This PR adds support for configuring the Web3Auth MFA levels, as described in [1]
CC @pyramation @NoahSaso 
[1]: https://web3auth.io/docs/sdk/pnp/web/no-modal/mfa#loginsettings
=> feat: add web3auth mfa level support

packages/docs/pages/provider/chain-provider.mdx
Corrected "beyound" to "beyond" for clarity and accuracy.
=> Typo fix chain-provider.mdx

packages/cosmos-kit/src/wallets.ts
This PR fixes a syntax error in the wallet array where an invalid decrement operator (--) was mistakenly included. The issue caused the module to fail parsing
- Replaced the incorrect syntax (-- - galaxystation) with the correct array spread for galaxystation.
- Ensured the array includes all necessary wallet integrations correctly.
- Verified that the module compiles without syntax errors.
- Confirmed functionality of wallet integrations.
=> fix: correct syntax issue with galaxystation in array

packages/docs/pages/advanced.md, packages/ins/README.md, packages/ins/src/name-service.ts
- **Fixed typos in `advanced.md`**  
- "necesssary" → "necessary"  
- **Fixed typos in `README.md`**  
- "Resovle" → "Resolve"  
- **Fixed typos in `name-service.ts`**  
- "accross" → "across"  
- `packages/docs/pages/advanced.md`  
- `packages/ins/README.md`  
- `packages/ins/src/name-service.ts`
=> Fix typos in documentation and `name-service.ts`

packages/core/package.json, packages/react-lite/package.json, packages/react/package.json, yarn.lock
nothing changed, just no need to stay on the release candidate version when v1.0.0 is published
=> bump cosmiframe to v1.0.0

packages/core/src/manager.ts
Related: #393
When you connect to chains, Cosmos Kit saves the accounts in local storage (in `cosmos-kit@2:core//current-wallet`). When visiting the site again and the wallet connection needs re-approval, it currently spams separate connection popups for each of the accounts stored in local storage, instead of doing a bulk connection like most wallets support. This PR aims to fix that to prevent the wallet spam.
Relevant code:
https://github.com/hyperweb-io/cosmos-kit/blob/60723793da672f5875d2132f1820584c7db52f8f/packages/core/src/manager.ts#L367-L413
and:
https://github.com/hyperweb-io/cosmos-kit/blob/60723793da672f5875d2132f1820584c7db52f8f/packages/core/src/manager.ts#L349-L365
The problem with this code is that `_restoreAccounts` does the following:
1. loads accounts from local …
=> Connect in bulk to accounts being restored from local storage
